[package]
name = "gbae"
version = "0.1.0"
edition = "2021"
rust-version = "1.87"
license = "MIT"
description = "A Game Boy Advance emulator"
repository = "https://github.com/Japabu/gbae"
readme = "README.md"

[lib]
path = "src/lib.rs"

[[bin]]
name = "gbae"
path = "src/main.rs"
required-features = ["frontend"]

[features]
default = ["frontend"]
frontend = ["dep:winit", "dep:softbuffer", "dep:cpal"]

[dependencies]
winit = { version = "0.30", optional = true }
softbuffer = { version = "0.4", optional = true }
cpal = { version = "0.18", optional = true }
image = { version = "0.25", default-features = false, features = ["png"] }
seq-macro = "0.3"

[profile.dev]
opt-level = 3

[profile.release]
lto = "fat"
codegen-units = 1
