[package]
name = "gbae"
version = "0.1.0"
edition = "2021"

[lib]
path = "src/lib.rs"

[[bin]]
name = "gbae"
path = "src/main.rs"
required-features = ["frontend"]

[features]
default = ["frontend"]
frontend = ["dep:winit", "dep:softbuffer", "dep:cpal", "dep:rfd"]

[dependencies]
winit = { version = "0.30", optional = true }
softbuffer = { version = "0.4", optional = true }
cpal = { version = "0.18", optional = true }
rfd = { version = "0.17", optional = true }
image = "0.25"
seq-macro = "0.3"

[profile.dev]
opt-level = 3

[profile.release]
lto = "fat"
codegen-units = 1
